# Generated by Django 5.1.1 on 2024-09-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workboard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workboard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workboard',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workboard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workboard',
            name='name',
            field=models.CharField(default='workboards', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To-Do', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
